FROM arm64v8/maven:3.6-amazoncorretto-8 AS group3SplendorBuild

##Source of Dockerfile :https://github.com/m5c/BoardGamePlatform.git
##Author of Source Files: maximilian schiedermeier

MAINTAINER Jafar Aliyev, Curtis Docherty, Yeping Li, Timothy Piggott, Antony Zhao, Yijie Zhang, Weichen Zong

##Prepare Maven environment
COPY server/src /usr/src/app/src
COPY server/pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package -P prod

##Prepare java environment
FROM openjdk:8-jre-alpine

##Wait for the start of ls
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

##Finished building, run the jar file and expose it to port 4244.
COPY --from=group3SplendorBuild /usr/src/app/target/SplendorApi.jar /usr/app/SplendorApi.jar
EXPOSE 4244

RUN apk add --no-cache bash coreutils grep sed