FROM arm64v8/maven:3.6-amazoncorretto-8 AS group3SplendorBuild

## Source of Dockerfile :https://github.com/m5c/BoardGamePlatform.git
## Author of Source Files: maximilian schiedermeier
## LobbyService and Most of content of Dockerfile of lobby service is from maximilian schiedermeier
## Usage directly of Dockerfile-ls-api from maximilian schiedermeier

COPY LobbyService/src /usr/src/app/src
COPY LobbyService/pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package -P prod

##Prepare java environment
FROM openjdk:8-jre-alpine

## Wait for the start of SQL
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

## Copy the jar file of lobby service to the java environment
COPY --from=group3SplendorBuild /usr/src/app/target/ls.jar /usr/app/ls.jar
EXPOSE 4242

## Run it with java environment
RUN apk add --no-cache bash coreutils grep sed
